### ISSUE TITLE
Update documentation to reflect current state of project

### ISSUE THREAD

**Issue by hynky1999** [hynky1999/CmonCrawl#90]
## TODO

- [ ] Update code docs to reflect changes in downloader
- [ ] Update cli docs to reflect changes in cli
- [ ] Add athena section
